# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI
run-name: Testing With Node.js

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Check Repository
      uses: actions/checkout@v3
    - name: Setup Node.js 16
      uses: actions/setup-node@v3
      with:
        always-auth: true
        node-version: 16.x
        registry-url: https://registry.npmjs.org
        scope: '@mtm-yinyinaye'
    - name: Install dependencies
      # run: npm ci
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      run: | 
        npm ci
        echo ${{ env.NODE_AUTH_TOKEN }}
    # cache: 'npm'
    # - run: npm ci
    # - run: npm run build --if-present
    # - run: npm test
